### ISSUE TITLE
msvc 2010 cannot be initialized using address of automatic variable 'user_locale'

### ISSUE THREAD

**Issue by raniervf** [mity/windrawlib#22]
Hi,
win/wdl/font.c(53) 
warning C4221: nonstandard extension used : 'locales' : cannot be initialized using address of automatic variable 'user_locale'

Is secure ignore this?
Best regards,

**Comment by mity** [comment]
I read the warning as yes: It would be error otherwise.

On the other side some super strict compilers might fail with that non-standard construction so please keep this issue open as a reminder for me. I'll improve the code to avoid the non-standard construction eventually. (I'm busy elsewhere right now.)

**Comment by raniervf** [comment]
Thank you.
