### ISSUE TITLE
Can we please have this in one VS2019 solution?

### ISSUE THREAD

**Issue by DBJDBJ** [mity/windrawlib#23]
For WIN10 PRO

**Comment by mity** [comment]
To be honest, I'm quite reluctant to maintain VS solution/project files because
1. different people tend to use different VS versions,
2. I do not use VS as a main development platform, and
3. there is the [CMake-based project support](https://devblogs.microsoft.com/cppblog/cmake-support-in-visual-studio/) in recent versions and it seems to work reasonably well. (Yes the building instructions in README.md do not cover this and that could likely be updated.)

If you really need the native solution files for some reason, feel free to cook a pull request, ideally in such a way that multiple solutions for different VS versions could co-exist (e.g. to place the solution files in a new subdir like "contrib/vs2019"). But note the bargain of maintaining it would be likely more or less on your shoulders.

**Comment by DBJDBJ** [comment]
Thanks for a reply :) 

I have to say I never understood people not using always the fully updated, free and the very best VS 2019.  While developing only on Win. That puzzles me.

Different VS versions? A puzzle again. Whats is better in any previous version vs the latest fully updated version?

I tried this lib this morning and it did not build with VS2019 WIN10 combo ...  I will try and reason with specific questions with new issue(s) ...

Kind regards ...

**Comment by mity** [comment]
Some people have codebases which are diffilult/expensive to migrate to new VS.

Also consider the bargain when e.g. VS 2020 or VS 2021 gets released. You cannot synchronize migration of all projects using the library.

**Comment by DBJDBJ** [comment]
All put together much less of a burden vs developing without the VS.
I update all the time. Our code has to build and work after each update.  Call it "VS Version agnostic".
Project which has a problem with the VS version is the priority. 

Mind you, VS is C#.  Not good. Also, SDK is ridiculously big and monolith. Not VS but a burden. 

...
